name: 🐛 Bug Report
description: Report a bug or unexpected behavior in NullByte
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the details below so we can investigate and fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the behavior.
      placeholder: |
        1. Launch NullByte
        2. Press Ctrl + Shift + S
        3. ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or paste relevant logs from `%APPDATA%/NullByte/logs/app.log`.
      placeholder: Paste screenshots or log output here...
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows 11
        - Windows 10
        - Windows (Other)
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: "Run `node -v` to check."
      placeholder: "e.g., v20.11.0"
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: NullByte Version
      description: "Check in package.json or the app title bar."
      placeholder: "e.g., 0.1.0-alpha"
    validations:
      required: false

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      options:
        - Built from source (npm run build)
        - Running in development (npm run start)
        - Pre-built .exe installer
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Add any other context here...
    validations:
      required: false
